---
# tasks file for roles/dhcpd
- name: Installation of dhcpd on Ubuntu
  apt:
    name: isc-dhcp-server
    state: latest
    update_cache: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Installation of dhcpd on CentOS
  yum:
    name: dhcp-server
    state: latest
    update_cache: yes
  when: ansible_facts['distribution'] == 'CentOS'
